name: docker-build-push

on:
  workflow_dispatch:
    inputs:
      repository:
        type: string
        required: true
      ref:
        type: string
        required: true
      token:
        type: string
        required: true
      username:
        type: string
        required: true
      password:
        type: string
        required: true
      context:
        type: string
        required: false
      tags:
        type: string
        required: true

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - 
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          token: ${{ inputs.token }}
      -
        uses: docker/setup-buildx-action@v3
      -
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}
      -
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ inputs.context }}"
          push: true
          tags: ${{ inputs.tags }}
